{% set name = "snorkel-metal" %}
{% set version = "0.1.0" %}
{% set file_ext = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash_value = "a0317439bd7269d9275472a5f4b09b91d907ea4b3be7bc0858e1ec01c55421c4" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  fn: '{{ name }}-{{ version }}.{{ file_ext }}'
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ file_ext }}
  '{{ hash_type }}': '{{ hash_value }}'

build:
  number: 0
  script: python -m pip install --no-deps --ignore-installed .
  skip: True  # [py<36]

requirements:
  build:
    - python=3.6
    - setuptools
  run:
    - python=3.6
    - matplotlib
    - networkx=2
    - nose
    - numpy
    - pandas
    - pytorch=0.4.1
    - scipy

test:
  imports:
    - metal
    - metal.end_model
    - metal.label_model
    - metal.modules
    - metal.multitask
    - metal.tuners
    - synthetic
    - tests
    - tests.metal
    - tests.metal.contrib
    - tests.metal.end_model
    - tests.metal.label_model
    - tests.metal.multitask
    - tests.metal.tuners
    - tests.synthetic
    - tests.travis

about:
  home: https://github.com/HazyResearch/metal
  license: Apache Software License
  license_family: APACHE
  license_file: LICENSE.txt
  summary: A system for quickly generating training data with multi-task weak supervision
  description: "# Snorkel MeTaL builds on [Snorkel](snorkel.stanford.edu) in an attempt to understand how _massively multi-task supervision and learning_ changes the way people program.\n_Multitask learning\
    \ (MTL)_ is an established technique that effectively pools samples by sharing representations across related _tasks_, leading to better performance with less training data (for a great primer of recent\
    \ advances, see [this survey](https://arxiv.org/abs/1706.05098)).\nHowever, most existing multi-task systems rely on two or three fixed, hand-labeled training sets.\nInstead, weak supervision opens\
    \ the floodgates, allowing users to add arbitrarily many _weakly-supervised_ tasks.\nWe call this setting _massively multitask learning_, and envision models with tens or hundreds of tasks with supervision\
    \ of widely varying quality.\nOur goal with the Snorkel MeTaL project is to understand this new regime, and the programming model it entails.\n\nMore concretely, Snorkel MeTaL is a framework for using\
    \ multi-task weak supervision (MTS), provided by users in the form of _labeling functions_ applied over unlabeled data, to train multi-task models.\nSnorkel MeTaL can use the output of labeling functions\
    \ developed and executed in [Snorkel](snorkel.stanford.edu), or take in arbitrary _label matrices_ representing weak supervision from multiple sources of unknown quality, and then use this to train\
    \ auto-compiled MTL networks.\n\nSnorkel MeTaL uses a new matrix approximation approach to learn the accuracies of diverse sources with unknown accuracies, arbitrary dependency structures, and structured\
    \ multi-task outputs.\nThis makes it significantly more scalable than our previous approaches.\n\n## References\n* **Best Reference: [_Training Complex Models with Multi-Task Weak Supervision_](https://ajratner.github.io/assets/papers/mts-draft.pdf)\
    \ [Technical Report]**\n* [Snorkel MeTaL: Weak Supervision for Multi-Task Learning](https://ajratner.github.io/assets/papers/deem-metal-prototype.pdf) [SIGMOD DEEM 2018]\n* _[Snorkel: Rapid Training\
    \ Data Creation with Weak Supervision](https://arxiv.org/abs/1711.10160) [VLDB 2018]_\n* _[Data Programming: Creating Large Training Sets, Quickly](https://arxiv.org/abs/1605.07723) [NIPS 2016]_"
  doc_url: ''
  dev_url: 'https://github.com/HazyResearch/metal'

extra:
  recipe-maintainers:
    - bhancock8
