{% set name = "snorkel-metal" %}
{% set version = "0.1.0" %}
{% set file_ext = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash_value = "a0317439bd7269d9275472a5f4b09b91d907ea4b3be7bc0858e1ec01c55421c4" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  fn: '{{ name }}-{{ version }}.{{ file_ext }}'
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ file_ext }}
  '{{ hash_type }}': '{{ hash_value }}'

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools
  run:
    - python >=3.6
    - matplotlib
    - networkx =2
    - numpy
    - pandas
    - pytorch =0.4.1
    - scipy

test:
  imports:
    - metal
    - metal.end_model
    - metal.label_model
    - metal.modules
    - metal.multitask
    - metal.tuners
    - synthetic
    - tests
    - tests.metal
    - tests.metal.contrib
    - tests.metal.end_model
    - tests.metal.label_model
    - tests.metal.multitask
    - tests.metal.tuners
    - tests.synthetic
    - tests.travis

about:
  home: https://github.com/HazyResearch/metal
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: A system for quickly generating training data with multi-task weak supervision
  description: "Snorkel MeTaL builds on [Snorkel](snorkel.stanford.edu) in an attempt to understand how _massively multi-task supervision and learning_ changes the way people program. See the README on the github repository for more information."
  doc_url: ''
  dev_url: 'https://github.com/HazyResearch/metal'

extra:
  recipe-maintainers:
    - bhancock8
